### ISSUE TITLE
[BUG] Settings Sub-Menus Not Displaying Correctly in Safari or Firefox

### ISSUE THREAD

**Issue by iocouto** [live-codes/livecodes#190]
Currently, if we go to the 'Settings' (i.e., 'cog') menu, and try to use the 'Save As', 'Export' or 'CSS Preset' sub-menus, strange UI glitches happen on both Safari and Firefox.

### SAFARI
The sub-menus display for about 0.25 second, and then they appear to get 'clipped' by the main menu, looking like this:

<img width="353" alt="Screen Shot 2021-12-07 at 1 58 38 pm" src="https://user-images.githubusercontent.com/75245963/144958912-4008ec1e-e51b-480c-b5d3-78e131b73e66.png">

### FIREFOX

The 'Save As' menu seems to display OK, but the 'Export' and 'CSS Preset' menus appear "split", with commands shown in 2 different locations in the viewport:

<img width="577" alt="Screen Shot 2021-12-07 at 2 00 43 pm" src="https://user-images.githubusercontent.com/75245963/144959249-56a06996-e7ee-4235-ba2b-89d98bf9bf40.png">

**Comment by hatemhosny** [comment]
I confirm I can reproduce the described behavior.
thank you for reporting

**Comment by hatemhosny** [comment]
This bug has now been fixed by #207 

you may test it on this [preview URL](https://88f1492e.livecodes.pages.dev/) or on [development build](https://dev.livecodes.io/)

It has been tested on chrome, firefox and safari

it should be available on livecodes.io with the next release.

@iocouto thank you for reporting and please let me know if you have any comments
