### ISSUE TITLE
[DOCS] Little Info on 'Deploy' Function Needed

### ISSUE THREAD

**Issue by iocouto** [live-codes/livecodes#191]
It would be super helpful to have a short little paragraph in the docs clarifying what the 'Deploy' command does, and what the requirements are to use it.

**Comment by hatemhosny** [comment]
@iocouto  thank you for showing interest in LiveCodes and helping to improve it.

I'm planning to create a separate documentation website with detailed description of how to use each feature with screenshots and code samples.

Meanwhile, this is a quick description:
The "Deploy" feature allows deploying the result web page (and optionally the source code) of a project to a publicly available web server, so that it can be tested, shared or even used for production.

It uses [GitHub pages](https://pages.github.com/) to host your project for free.

You have to login via github (allowing access to repos).
Then you choose either to create a new github repo under you account or use an existing one.
The result (compiled) page with be pushed to the selected repo under the branch `gh-pages`
this allows you to access the page with the url: `https://{youraccount}.github.io/{project}`

the css and js are hosted as separate files

this is a demo:
https://hatemhosny.github.io/react-starter-demo/
repo: https://github.com/hatemhosny/react-starter-demo
gh-branch: https://github.com/hatemhosny/react-starter-demo/tree/gh-pages

I hope this helps to get you started and please let me know if you have any inquiries or suggestions

**Comment by hatemhosny** [comment]
This is now documented here:

https://livecodes.io/docs/features/deploy
