### ISSUE TITLE
[DOCS]  How to Use Images

### ISSUE THREAD

**Issue by iocouto** [live-codes/livecodes#192]
It may not be immediately obvious to a new developer playing with code in their local machine that they cannot easily 'add' or 'import' an image from their own local computer to their LiveCode pen. It would be helpful to have a little section in the docs that explains how to use images into the pens. Some of the ways I can think of may include:

1) using a public image URL - the URL of an image that is publicly available on the internet - while their computer is connected to the internet

2) embedding the image as encoded data - eg., base64 encoded

3) Using a local server that can serve their local images via URLs that are resolved by their local machine - eg., if using tools that create virtual servers in their machines, such as MAMP/XAMPP, Nginx, Apache, Node, PHP, etc.

Are there any other ways?...

**Comment by hatemhosny** [comment]
This is a nice suggestion.

adding images or other assets to projects is a real need.

I agree to your methods 1 & 2.
method 3 (in addition to being technically challenging/out of scope) will not allow sharing your project because it depends on local resources.

Having a self-contained projects that you can easily share and re-edit is an important goal for LiveCodes.

On the other hand, your suggestion made me think of having UI to add local files. The app would give you a url for that file which is either:
1. base64-encoded data url
2. url of the file uploaded to a public server (e.g. github pages)

thank you

**Comment by hatemhosny** [comment]
hi @iocouto,

based on your suggestion, the app now allows adding assets (like images, videos, scripts, stylesheets, icons or any other files).

in the settings menu look for "Assets..."

It allows adding local files as base64-encoded data url or deploys the files to GitHub pages (on `livecodes-assets` repo on your account). You then get the url to use in your projects.
The urls are locally saved in your browser and can be easily re-used across projects.

you may try it on the development build:
https://dev.livecodes.io/

or directly open assets
https://dev.livecodes.io/?screen=assets

please let me know if you have any comments or suggestions

Thank you :)

**Comment by hatemhosny** [comment]
This is now documented here:

https://livecodes.io/docs/features/assets
