### ISSUE TITLE
can not load https://livecodes-sandbox.pages.dev/v4/compiler

### ISSUE THREAD

**Issue by tiger8888** [live-codes/livecodes#290]
when i run `npm run serve` , the browser can not load https://livecodes-sandbox.pages.dev/v4/compiler,is this close source?

**Comment by hatemhosny** [comment]
It is this page:
https://github.com/live-codes/livecodes/blob/develop/src/livecodes/html/sandbox/v5/compiler.html

It is just being served from a different origin for [security reasons](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#cross-origin_script_api_access).

I believe your problem is solved since you already closed the issue.

However, this is how you serve the app:
```sh
# clone the repo
git clone https://github.com/live-codes/livecodes

# move into the directory 
cd livecodes

# install dependencies 
npm i

# build the app
npm run build

# then you can serve it from the directory "build"
npm run serve
```

I hope this helps.
Please let me know if you still face any problems.

**Comment by aehlke** [comment]
Sorry to revive this issue - is there a way to serve the compiler.html page from my own host? I haven't yet tracked down how this livecodes-sandbox.pages.dev iframe src gets loaded / how to influence that. Would also appreciate any update on offline mode. Thank you

**Comment by hatemhosny** [comment]
You may change the URL in the sandbox service, here: https://github.com/live-codes/livecodes/blob/develop/src/livecodes/services/sandbox.ts

I have not started work on offline mode, yet.

Currently, preparing for public release/announcements.

**Comment by aehlke** [comment]
Thank you, got it! And good luck!
