### ISSUE TITLE
CLI headless builds

### ISSUE THREAD

**Issue by aehlke** [live-codes/livecodes#473]
### Type of feature

✨ Feature

### Suggested feature

Would be convenient to have an easy CLI method of building inputs and accessing the result code. I’m guessing it would need to invoke something like playwright but not for testing. Not sure the easiest way to achieve this or if there’s a good way to avoid needing the full browser in headless mode

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by hatemhosny** [comment]
wow!
this is probably taking it to the extreme :)

this would be out of scope of this project, however, I would be really interested to know if someone creates such a project on top of LiveCodes.

Thank you for the creative ideas and please keep pushing the limits :)

**Comment by aehlke** [comment]
Well my applications of this are taking an amazingly well done lowest common denominator and scaling it up to keep the foundations easy to work with and extensible. It's complicated but simple at the same time. I've also added real-time data sync to the web layer with RxDB syncing to iOS/macOS data in turn syncing to iCloud and backend as needed, all automatically for all data models. So it's very flexible for me. I hope to open source this later once I figure out cross platform Swift more than these early experiments with mobile and web.

Could you suggest whether this needs playwright or could work in a non-browser node environment with virtual dom? I can probably just package this into a docker CLI command most easily. My intention is to use livecodes for publishing content to web from mobile and from CI, either way. I'm trying to maximize my code reuse instead of use a different build system elsewhere.

**Comment by hatemhosny** [comment]
Desktop/CLI apps are not my area of experience. However, LiveCodes uses multiple iframes and web workers that communicate using `postMessage`. In addition, many web APIs are used. I'm not sure if that would work on a virtual DOM implementation. I know playwright works because I use it for [e2e tests](https://github.com/live-codes/livecodes/tree/develop/e2e).
Another direction to explore (which I know nothing about) is using something like electron or tauri. May be check this: https://tauri.app/v1/guides/features/cli/

Again, this is not where I can help or think LiveCodes should include in its core. But it is an area where I would be happy to see other apps cover.

**Comment by aehlke** [comment]
Thanks for the context. I'll try Tauri, didn't know about that, very interesting - or wrapping Playwright in a simple CLI command interface to use for running builds and extracting the result.
